# Generated by Django 2.2.5 on 2021-01-02 07:59

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=25, unique=True)),
                ('exam_subject', models.CharField(max_length=25)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('activation_date', models.DateField()),
                ('prepared_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_question_types', models.CharField(choices=[('SB', 'Subjective'), ('OB', 'Objective')], default='Subjective', max_length=5)),
                ('question', models.TextField()),
                ('correct_answers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=8)),
                ('wrong_answers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=8)),
                ('exam_info', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam_module.Exam_Info')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_dict', django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('exam_info', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam_module.Exam_Info')),
                ('student_name', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
